### ISSUE TITLE
ACM v0.2 - Vertical Arcade games rotated

### ISSUE THREAD

**Issue by lucke** [acm-cfw/acm-cfw.github.io#30]
When using the v0.2 pre-release of the ACM if you run a vertical arcade game it appears rotated 90 degrees inside a vertical display on the 16:9 screen. It's very weird.

None of the normal retroarch rotation options when in the game fix the issue.

Tried with several vertical games with the same result. I believe this worked on v0.1 but can't confirm.

**Comment by ftirador** [comment]
> When using the v0.2 pre-release of the ACM if you run a vertical arcade game it appears rotated 90 degrees inside a vertical display on the 16:9 screen. It's very weird.
> 
> None of the normal retroarch rotation options when in the game fix the issue.
> 
> Tried with several vertical games with the same result. I believe this worked on v0.1 but can't confirm.

inside a system (eg mame) push select (list options),advanced options, and: vertical rotation (tate) to off and allow rotation set to off

**Comment by lucke** [comment]
@fakemaria  thank you! Solved with these settings.

**Comment by ftirador** [comment]
@acmeplus that settings is worth it to add it in a faq for acm
